#!/bin/bash

/home/hts/hts2019/openpose/build/examples/openpose/openpose.bin --video /home/hts/hts2019/openpose/video/a/1.avi --write_json "/home/hts/hts2019/openpose/video_res/Res_json/a" --write_images "/home/hts/hts2019/openpose/video_res/Res_img/a" --write_video "/home/hts/hts2019/openpose/video_res/Res_video/a/1.avi"
/home/hts/hts2019/openpose/build/examples/openpose/openpose.bin --video /home/hts/hts2019/openpose/video/a/2.avi --write_json "/home/hts/hts2019/openpose/video_res/Res_json/a" --write_images "/home/hts/hts2019/openpose/video_res/Res_img/a" --write_video "/home/hts/hts2019/openpose/video_res/Res_video/a/2.avi"
/home/hts/hts2019/openpose/build/examples/openpose/openpose.bin --video /home/hts/hts2019/openpose/video/a/3.avi --write_json "/home/hts/hts2019/openpose/video_res/Res_json/a" --write_images "/home/hts/hts2019/openpose/video_res/Res_img/a" --write_video "/home/hts/hts2019/openpose/video_res/Res_video/a/3.avi"

/home/hts/hts2019/openpose/build/examples/openpose/openpose.bin --video /home/hts/hts2019/openpose/video/b/1.avi --write_json "/home/hts/hts2019/openpose/video_res/Res_json/b" --write_images "/home/hts/hts2019/openpose/video_res/Res_img/b" --write_video "/home/hts/hts2019/openpose/video_res/Res_video/b/1.avi"
/home/hts/hts2019/openpose/build/examples/openpose/openpose.bin --video /home/hts/hts2019/openpose/video/b/2.avi --write_json "/home/hts/hts2019/openpose/video_res/Res_json/b" --write_images "/home/hts/hts2019/openpose/video_res/Res_img/b" --write_video "/home/hts/hts2019/openpose/video_res/Res_video/b/2.avi"
/home/hts/hts2019/openpose/build/examples/openpose/openpose.bin --video /home/hts/hts2019/openpose/video/b/3.avi --write_json "/home/hts/hts2019/openpose/video_res/Res_json/b" --write_images "/home/hts/hts2019/openpose/video_res/Res_img/b" --write_video "/home/hts/hts2019/openpose/video_res/Res_video/b/3.avi"

/home/hts/hts2019/openpose/build/examples/openpose/openpose.bin --video /home/hts/hts2019/openpose/video/c/1.avi --write_json "/home/hts/hts2019/openpose/video_res/Res_json/c" --write_images "/home/hts/hts2019/openpose/video_res/Res_img/c" --write_video "/home/hts/hts2019/openpose/video_res/Res_video/c/1.avi"
/home/hts/hts2019/openpose/build/examples/openpose/openpose.bin --video /home/hts/hts2019/openpose/video/c/2.avi --write_json "/home/hts/hts2019/openpose/video_res/Res_json/c" --write_images "/home/hts/hts2019/openpose/video_res/Res_img/c" --write_video "/home/hts/hts2019/openpose/video_res/Res_video/c/2.avi"
/home/hts/hts2019/openpose/build/examples/openpose/openpose.bin --video /home/hts/hts2019/openpose/video/c/3.avi --write_json "/home/hts/hts2019/openpose/video_res/Res_json/c" --write_images "/home/hts/hts2019/openpose/video_res/Res_img/c" --write_video "/home/hts/hts2019/openpose/video_res/Res_video/c/3.avi"

/home/hts/hts2019/openpose/build/examples/openpose/openpose.bin --video /home/hts/hts2019/openpose/video/d/1.avi --write_json "/home/hts/hts2019/openpose/video_res/Res_json/d" --write_images "/home/hts/hts2019/openpose/video_res/Res_img/d" --write_video "/home/hts/hts2019/openpose/video_res/Res_video/d/1.avi"
/home/hts/hts2019/openpose/build/examples/openpose/openpose.bin --video /home/hts/hts2019/openpose/video/d/2.avi --write_json "/home/hts/hts2019/openpose/video_res/Res_json/d" --write_images "/home/hts/hts2019/openpose/video_res/Res_img/d" --write_video "/home/hts/hts2019/openpose/video_res/Res_video/d/2.avi"
/home/hts/hts2019/openpose/build/examples/openpose/openpose.bin --video /home/hts/hts2019/openpose/video/d/3.avi --write_json "/home/hts/hts2019/openpose/video_res/Res_json/d" --write_images "/home/hts/hts2019/openpose/video_res/Res_img/d" --write_video "/home/hts/hts2019/openpose/video_res/Res_video/d/3.avi"

/home/hts/hts2019/openpose/build/examples/openpose/openpose.bin --video /home/hts/hts2019/openpose/video/e/1.avi --write_json "/home/hts/hts2019/openpose/video_res/Res_json/e" --write_images "/home/hts/hts2019/openpose/video_res/Res_img/e" --write_video "/home/hts/hts2019/openpose/video_res/Res_video/e/1.avi"
/home/hts/hts2019/openpose/build/examples/openpose/openpose.bin --video /home/hts/hts2019/openpose/video/e/2.avi --write_json "/home/hts/hts2019/openpose/video_res/Res_json/e" --write_images "/home/hts/hts2019/openpose/video_res/Res_img/e" --write_video "/home/hts/hts2019/openpose/video_res/Res_video/e/2.avi"
/home/hts/hts2019/openpose/build/examples/openpose/openpose.bin --video /home/hts/hts2019/openpose/video/e/3.avi --write_json "/home/hts/hts2019/openpose/video_res/Res_json/e" --write_images "/home/hts/hts2019/openpose/video_res/Res_img/e" --write_video "/home/hts/hts2019/openpose/video_res/Res_video/e/3.avi"
